import 'dart:convert';

import 'package:dio/dio.dart';
import 'package:uas/model/model.dart';

Future<List<Autogenerated>> getData() async{
  BaseOptions options = BaseOptions(
      baseUrl: "https://jsonplaceholder.typicode.com",
      connectTimeout: 3000,
      receiveTimeout: 3000,
    );
    Dio dio = Dio(options);
    Response resp = await dio.get(
      "/posts"
    );

    return resp.data.map<Autogenerated>(Autogenerated.fromJson).toList();
    
}