class Autogenerated {
  final int userId;
  final int id;
  final String title;
  final String body;

  const Autogenerated({
    required this.userId,
    required this.id,
    required this.title,
    required this.body,
  });

  static Autogenerated fromJson(json) {
    return Autogenerated(
      userId: json['userId'],
      id: json['id'],
      title: json['title'],
      body: json['body'],
    );
  }
}